version: "3.7"
services:
  db:
    image: postgres:12.2-alpine
    ports:
      - "64320:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "max_connections=15"]
